apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../overlay
patchesJson6902:
- target:
    version: v1
    kind: Pod
    name: nginx
  path: add_env.yaml
- target:
    version: v1
    kind: Pod
    name: nginx
  path: replace_env.yaml
