apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
      env:
        - name: DEMO_GREETING
          value: 'Hello from the environment'
        - name: DEMO_HELLO
          value: 'Hello from overlay'
